_target_: src.models.livi.LIVIadvBatchSex

x_dim: 1815
y_dim: 981
z_dim: 100
exbatch_dim: 2
donor_sex_dim: 2
encoder_hidden_dims: [512, 512, 512]
learning_rate: 8e-4
layer_norm: True
likelihood: nb_batch_sex
adversary_weight: 100
adversary_hidden_dims: [256, 256, 256]
adversary_learning_rate: 1e-4
adversary_steps: 2
device: cuda
