# Pretrain VAE and global genetic effects, before learning context-specific genetic effects

pretrain_livi:
  _target_: src.callbacks.pretrain_livi.LIVIPretrain
  pretrain_vae_epochs: 10
  pretrain_wo_GxC_epochs: 10